name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: bash configure
      
    - name: Build
      run: make pro

    - name: Download Output
      uses: actions/upload-artifact@v2
      with:
          name: HelloWorldProOS
          path: isoOutput
